#!/bin/bash

. ./.secret

match=$1
question=$2
timestamp=$3

if [ -z $match ]; then
   firebase --project ${project} --token ${token} database:get /v0/live-matches | jq '[. | to_entries[] | {"id": .key, "home": .value.home, "away": .value.away}]'
   echo "Enter Match ID (valid IDs above):"
   read match
fi

if [ -z $question ]; then
   echo "Enter the question you'd like to ask:"
   read question
fi

if [ -z $timestamp ]; then
   echo "Enter the match time in the format XXmin:"
   read timestamp
fi

asked=$(gdate -u --rfc-3339=seconds | sed 's/ /T/')
uuid=$(uuidgen | tr 'A-Z' 'a-z')

json=$(echo '[{"asked": "'${asked}'","decision": "","description": "","id": "'${uuid}'","question": "'${question}'","time": "'${timestamp}'"}]')

firebase --project ${project} --token ${token} database:get /v0/live-matches/${match}/questions | jq ". |= .+ $json" | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-matches/${match}/questions
