#!/bin/bash

. ./.secret

match=$1
timestamp=$2
group=$3

if [ -z $match ]; then
   firebase --project ${project} --token ${token} database:get /v0/live-matches | jq '[. | to_entries[] | {"id": .key, "home": .value.home, "away": .value.away}]'
   echo "Enter Match ID (valid IDs above):"
   read match
fi

if [ -z $timestamp ]; then
   echo "Enter the match time in the format XXmin:"
   read timestamp
fi

if [ -z $group ]; then
   echo "Enter the group header:"
   read group
fi

gid=$(uuidgen | tr 'A-Z' 'a-z')

function question {
   asked=$(gdate -u --rfc-3339=seconds | sed 's/ /T/')
   uuid=$(uuidgen | tr 'A-Z' 'a-z')

   echo "Enter the question:"
   read question
}

function question_json {
   echo '{"id": "'${uuid}'", "asked": "'${asked}'","decision": "","description": "","question": "'${question}'"}'
}

function question_id_json {
  echo '[{"id": "'${uuid}'"}]'
}

function stats_json {
  echo '{"id": "'${uuid}'", "simple": {"yes": 0, "no": 0}}'
}

question
question_json | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-questions/${uuid}
stats_json | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-statistics/${uuid}

ids_json=$(question_id_json)

while :
do
   echo "Another question? [Y/n]"
   read another

   case $another in
      [Yy] | "" )
         question
         tmp=$(question_id_json)
         question_json | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-questions/${uuid}
         stats_json | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-statistics/${uuid}
         ids_json=$(echo $ids_json | jq ". |= .+ $tmp")
         ;;
      [Nn] )
         break
         ;;
      *)
         echo "Sorry what? Say Y or N pls."
         ;;
   esac
done

asked=$(gdate -u --rfc-3339=seconds | sed 's/ /T/')
json='[{"gid":"'${gid}'", "group":"'${group}'", "time": "'${timestamp}'", "asked":"'${asked}'", "questions": '$ids_json'}]'

echo ${json} | jq

echo "This ok? (hit enter if yeah, hit ctrl-c if nah)"
read

firebase --project ${project} --token ${token} database:get /v0/live-matches/${match}/questions | jq ". |= .+ $json" | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-matches/${match}/questions
