#!/bin/bash

. ./.secret

home=$1
away=$2
referee=$3

if [ -z $home ]; then
   echo "Enter Home Team:"
   read home
fi

if [ -z $away ]; then
   echo "Enter Away Team:"
   read away
fi

if [ -z $referee ]; then
   echo "Enter the match referee:"
   read referee
fi

if [ -z $kick_off ]; then
   echo "Enter the kick off time - IMPORTANT: this must be in the format YYYY-MM-DDTHH:MM:SS.000, and MUST be in UTC (i.e. one hour behind the UK)"
   read kick_off
fi

uuid=$(uuidgen | tr 'A-Z' 'a-z')
json='{"id": "'${uuid}'","home": "'$home'","away": "'$away'","home_score": 0,"away_score": 0,"home_lineup": [], "home_subs": [], "away_lineup": [], "away_subs": [], "kick_off": "'${kick_off}'", "referee": "'$referee'"}'

echo $json | jq

echo "This ok? (hit enter if yeah, hit ctrl-c if nah)"
read
